apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bind9
  name: bind9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: ubuntu/bind9:edge
        env:
        - name: DOCKER_LOGS
          value: 1
        - name: ALLOW_QUERY
          value: any
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
