apiVersion: v1
kind: Service
metadata:
  namespace: bind9
  name: bind9-service
  labels:
    app: bind9
spec:
  type: NodePort
  selector:
    app: bind9
  ports:
  - protocol: TCP
    nodePort: 32400
    port: 5353
    targetPort: 53
    name: bind9-tcp
  - protocol: UDP
    port: 5353
    targetPort: 53
    name: bind9

