apiVersion: v1
kind: Service
metadata:
  namespace: solar-system
  labels:
    app: solar-system
  name: solar-system
spec:
  selector:
    app: solar-system
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
